name: Bug report
description: Something isn't working correctly
labels: ["bug", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to file a bug report. Please fill out as much as you can.

  - type: dropdown
    id: component
    attributes:
      label: Component
      options:
        - clawd (daemon)
        - Desktop app (macOS / Windows / Linux)
        - Mobile app (iOS / Android)
        - clawd_client package
        - clawd_proto package
        - clawd_core package
        - clawd_ui package
        - Other
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      placeholder: "e.g. v0.3.1 or commit SHA"
    validations:
      required: true

  - type: input
    id: os
    attributes:
      label: OS / Platform
      placeholder: "e.g. macOS 15.2, Ubuntu 24.04, iOS 18"
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: What happened?
      placeholder: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: What did you expect?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Open ClawDE
        2. Start a session in repo X
        3. Send message Y
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: Paste any relevant daemon logs or stack traces.
      render: text
