-- Migration 021: Autonomous Execution Engine (Sprint J, AE.T01–AE.T14)
--
-- ae_plans: JIRA-style task specs generated by the orchestration turn before
--   each user message is dispatched. One plan per message (or one per session
--   for complex sessions). Approved plans unlock execution.
--
-- ae_decisions: key decisions recorded during a session to prevent conflicting
--   proposals later (AE.T06). Indexed per session.
--
-- task_reviews: CR results from the self-QA gate and cross-provider code review
--   agent (AE.T08–AE.T10). Graded A-F; minimum B- to pass.

-- ─── ae_plans ─────────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ae_plans (
    id                  TEXT    NOT NULL PRIMARY KEY,
    session_id          TEXT    NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    title               TEXT    NOT NULL,
    -- JSON array of requirement strings (Vec<String>)
    requirements        TEXT    NOT NULL DEFAULT '[]',
    -- JSON array of definition-of-done strings
    definition_of_done  TEXT    NOT NULL DEFAULT '[]',
    -- JSON array of expected file paths (Vec<PathBuf> serialised as strings)
    files_expected      TEXT    NOT NULL DEFAULT '[]',
    -- AI instruction block injected into the system prompt
    ai_instructions     TEXT    NOT NULL DEFAULT '',
    created_at          TEXT    NOT NULL,
    -- NULL until the user taps "Approve Plan" in the Flutter UI
    approved_at         TEXT
);

CREATE INDEX IF NOT EXISTS idx_ae_plans_session
    ON ae_plans(session_id, created_at DESC);

-- ─── ae_decisions ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS ae_decisions (
    id          TEXT    NOT NULL PRIMARY KEY,
    session_id  TEXT    NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    -- Short description, e.g. "chose SQLite over Postgres"
    description TEXT    NOT NULL,
    -- Free-form JSON blob with rationale, alternatives considered, etc.
    context     TEXT    NOT NULL DEFAULT '{}',
    created_at  TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_ae_decisions_session
    ON ae_decisions(session_id, created_at DESC);

-- ─── task_reviews ─────────────────────────────────────────────────────────────

CREATE TABLE IF NOT EXISTS task_reviews (
    id                TEXT    NOT NULL PRIMARY KEY,
    -- References the ae_plans.id that this review is for
    task_id           TEXT    NOT NULL,
    -- Letter grade: A | B | B- | C | D | F
    grade             TEXT    NOT NULL,
    -- JSON array of finding strings
    findings          TEXT    NOT NULL DEFAULT '[]',
    -- Provider that performed the review (e.g. "claude", "codex")
    reviewer_provider TEXT    NOT NULL DEFAULT '',
    created_at        TEXT    NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_task_reviews_task
    ON task_reviews(task_id, created_at DESC);

-- ─── parent_task_id (AE.T14 genealogy addendum) ───────────────────────────────
--
-- Adds a self-referencing parent_task_id to ae_plans so that sub-tasks
-- generated during a session can be linked back to their parent plan.
-- NULL = top-level plan (no parent).

ALTER TABLE ae_plans ADD COLUMN parent_task_id TEXT REFERENCES ae_plans(id);
