//! Generate `.codex/config.toml` from `.claw/` policies.
//!
//! `clawd init-claw` (or `clawd init`) writes this file so that the Codex CLI
//! picks up the sandbox, approval, and rules settings that match the project's
//! governance policies.

use std::path::Path;

// ─── Config generation ────────────────────────────────────────────────────────

/// Generate the TOML content for `.codex/config.toml`.
///
/// The generated file wires up Codex's sandbox, approval gates, and rule
/// paths to the corresponding directories inside `.claw/`.
///
/// # Example
///
/// ```no_run
/// use clawd::agents::codex_config::generate_codex_config;
/// let toml = generate_codex_config(std::path::Path::new("/project/.claw"));
/// assert!(toml.contains("[sandbox]"));
/// ```
pub fn generate_codex_config(claw_dir: &Path) -> String {
    format!(
        r#"# Generated by clawd from .claw/policies/
# Do not edit manually — regenerate with: clawd init-claw

[sandbox]
network = false
writable_roots = ["{worktrees}"]

[approval]
auto_approve_tools = ["read_file", "search_files", "log_event", "run_tests"]
require_approval_tools = ["apply_patch", "request_approval"]

[rules]
policy_dir = "{policies}"
templates_dir = "{templates}"
"#,
        worktrees = claw_dir.join("worktrees").display(),
        policies = claw_dir.join("policies").display(),
        templates = claw_dir.join("templates").display(),
    )
}

/// Write `.codex/config.toml` into the given project directory.
///
/// Creates the `.codex/` directory if it does not exist.
pub async fn write_codex_config(project_dir: &Path, claw_dir: &Path) -> anyhow::Result<()> {
    let codex_dir = project_dir.join(".codex");
    tokio::fs::create_dir_all(&codex_dir).await?;
    let content = generate_codex_config(claw_dir);
    tokio::fs::write(codex_dir.join("config.toml"), content).await?;
    Ok(())
}

// ─── Tests ────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn config_contains_required_sections() {
        let claw = std::path::Path::new("/tmp/test-project/.claw");
        let toml = generate_codex_config(claw);
        assert!(toml.contains("[sandbox]"), "missing [sandbox]");
        assert!(toml.contains("[approval]"), "missing [approval]");
        assert!(toml.contains("[rules]"), "missing [rules]");
        assert!(toml.contains("network = false"), "missing network = false");
        assert!(toml.contains("worktrees"), "missing worktrees path");
        assert!(toml.contains("policies"), "missing policies path");
        assert!(toml.contains("templates"), "missing templates path");
    }

    #[test]
    fn config_embeds_claw_paths() {
        let claw = std::path::Path::new("/my/project/.claw");
        let toml = generate_codex_config(claw);
        assert!(toml.contains("/my/project/.claw/worktrees"));
        assert!(toml.contains("/my/project/.claw/policies"));
        assert!(toml.contains("/my/project/.claw/templates"));
    }
}
